FROM golang:1.22 AS builder
WORKDIR /app
COPY service_a/ .
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o service-a main.go

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/service-a .
CMD ["./service-a"]